# Generated by Django 4.2.30 on 2026-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_easteregg_alter_contest_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemeasteregg',
            name='tag',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('AC', 'Accepted'), ('PAC', 'Partially Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('IR', 'Invalid Return'), ('RTE', 'Runtime Error'), ('CE', 'Compile Error'), ('IE', 'Internal Error'), ('SC', 'Short Circuited'), ('AB', 'Aborted')], help_text='The submission result tag that triggers this Easter egg (e.g. IN_PROGRESS, AC, WA, TLE).', max_length=50, verbose_name='trigger tag'),
        ),
    ]
