# Generated by Django 4.2.30 on 2026-09-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_create_org_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'exam category',
                'verbose_name_plural': 'exam categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'exam province',
                'verbose_name_plural': 'exam provinces',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('year', models.IntegerField(verbose_name='year')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('description', models.TextField(blank=True, help_text='Markdown supported', verbose_name='description')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('problem_count', models.IntegerField(default=0, verbose_name='problem count')),
                ('total_points', models.FloatField(default=0, verbose_name='total points')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='judge.examcategory', verbose_name='category')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='judge.examprovince', verbose_name='province')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_problems', to='judge.exam', verbose_name='exam')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='judge.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'exam problem',
                'verbose_name_plural': 'exam problems',
                'ordering': ['order'],
                'unique_together': {('exam', 'problem')},
            },
        ),
    ]
