# Generated by Django 4.2.30 on 2026-09-11 17:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def backfill_search_vector(apps, schema_editor):
    """Backfill search_vector for all existing Problem records."""
    Problem = apps.get_model('judge', 'Problem')
    # Use raw SQL for efficient batch update
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE judge_problem
            SET search_vector = to_tsvector('english',
                coalesce(code, '') || ' ' ||
                coalesce(name, '') || ' ' ||
                coalesce(description, '')
            )
            WHERE search_vector IS NULL
        """)


def reverse_backfill(apps, schema_editor):
    """Clear search_vector values."""
    Problem = apps.get_model('judge', 'Problem')
    Problem.objects.update(search_vector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0239_examcategory_examprovince_exam_examproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='search vector'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='problem_search_vector_gin_idx'),
        ),
        migrations.RunPython(backfill_search_vector, reverse_backfill),
    ]
