# Generated by Django 4.2.30 on 2026-09-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0241_rebackfill_search_vector_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='', help_text='Relative path to user avatar WebP image under media.', max_length=255, verbose_name='avatar image path'),
        ),
    ]
