# Generated by Django 4.2.30 on 2026-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0242_add_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.CharField(blank=True, default='', help_text='Relative path to user custom background WebP image under media.', max_length=255, verbose_name='custom background image path'),
        ),
    ]
