# Generated by Django 4.2.30 on 2026-10-07 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0243_add_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='public visibility'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='publish_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='publish date'),
        ),
        migrations.CreateModel(
            name='SolutionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=7, verbose_name='language')),
                ('content', models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='translated editorial content')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='judge.solution', verbose_name='solution')),
            ],
            options={
                'verbose_name': 'solution translation',
                'verbose_name_plural': 'solution translations',
                'unique_together': {('solution', 'language')},
            },
        ),
    ]
